### ISSUE TITLE
Startup problem

### ISSUE THREAD

**Issue by th3vital** [ErkanMDR/Linux-CapsLock-Delay-Fixer#1]
Hi, i am having a problem putting the command in startup. Every time i do it the caps lock is disabled during startup. However, when i launch it after startup... it works

**Comment by ErkanMDR** [comment]
What distro system are you using?

**Comment by th3vital** [comment]
Linux mint.... maybe i am doing it wrong...

**Comment by th3vital** [comment]
I just found out what the issue is. The problem is that i extracted the whole folder in the downloads folder. So, when it tries to run your script it doesn't find the other files because the terminal think it's on the home folder. 
What I did is:
extract the files (not the folder inside home), then i made a .desktop file inside /etc/xdg/autostart that has a shortcut to open the sh file inside the home folder.
